### ISSUE TITLE
Use -extra-plugins

### ISSUE THREAD

**Issue by probonopd** [patrickelectric/mini-qml#1]
https://github.com/patrickelectric/mini-qml/blob/0f061c8a4f42eaa0712a1fbf6cc8668f5c2c34aa/.travis.yml#L62-L63

You may consider to use the `linuxdeployqt` option `-extra-plugins=<list>` instead. More information: https://github.com/probonopd/linuxdeployqt/#adding-extra-qt-plugins

`-extra-plugins=imageformats/libqsvg.so` might do the trick.

**Comment by patrickelectric** [comment]
Hi @probonopd 	is always a pressure to see you around !
This was already done in: fc76dff149aa9699a0c6b253edbbdbc3322281a0
Be free to give any other issue :)

**Comment by probonopd** [comment]
Hopefully you meant _pleasure_ ;-)
