### ISSUE TITLE
Linux Download link gives 404 Error

### ISSUE THREAD

**Issue by Light-Wizzard** [patrickelectric/mini-qml#5]
Linux Download link:

https://github.com/patrickelectric/mini-qml/releases/download/continuous/mini-qml-x86_64.AppImage

gives 404 Error, page not found.

**Comment by patrickelectric** [comment]
Thank you, indeed there is an error in my README.
You can download it from github releases webpage:
https://github.com/patrickelectric/mini-qml/releases/download/continuous/mini-qml.AppImage

**Comment by patrickelectric** [comment]
Fixed with 6670895
